/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sss.durianproductiontracker;

import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class frmDisplayDateFromTo extends javax.swing.JFrame {

    /**
     * Creates new form frmDisplayDateFromTo
     */
    public frmDisplayDateFromTo() {
        initComponents();
    }
    
    public frmDisplayDateFromTo(int y, int m, int d, int count) {
        initComponents();
        populateTableReceived(y,m,d,count);
        populateTableOpened(y,m,d,count);
        populateTablePackaged(y,m,d,count);
        populateTableSeparated(y,m,d,count);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableReceived = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOpened = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTablePackaged = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTableSeparated = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Batches of <DATE>");

        jTableReceived.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date Recieved", "Variety", "Quality", "Harvest Type", "Fruit Weight", "Recieved Pieces", "Current Process", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTableReceived);

        jTabbedPane1.addTab("Received", jScrollPane8);

        jTableOpened.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date Opened", "Date Recieved", "Variety", "Quality", "Harvest Type", "Pulp Weight", "Opened Pieces", "Current Process", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableOpened);

        jTabbedPane1.addTab("Opened", jScrollPane1);

        jTablePackaged.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date Packaged", "Date Opened", "Date Recieved", "Variety", "Quality", "Harvest Type", "Pieces Packaged", "Current Process", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(jTablePackaged);

        jTabbedPane1.addTab("Packaged", jScrollPane9);

        jTableSeparated.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date Separated", "Date Opened", "Date Recieved", "Variety", "Quality", "Harvest Type", "Color", "Meat w/ Seeds", "Meat w/o Seeds", "Current Process", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(jTableSeparated);

        jTabbedPane1.addTab("Separated", jScrollPane10);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("OKAY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(526, 526, 526)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void populateTableSeparated(int year, int month, int date, long number){
        DefaultTableModel tblModel = (DefaultTableModel)jTableSeparated.getModel();
        LocalDate dateStart = LocalDate.of(year, month, date);
        
        long i = 0;
        while(i != number){
        
            int count = 0;  
        
        while(count != separationController.SList.getList().size()){
             
            if(separationController.SList.getList().get(count).equalsDate(dateStart) != false){
            
            tblModel.addRow(new Object[] {separationController.SList.getList().get(count).getDateSeparation(),
                                        separationController.SList.getList().get(count).getDateOpened(),
                                        separationController.SList.getList().get(count).getDateRecieved(),
                                        separationController.SList.getList().get(count).getVrty(),
                                        separationController.SList.getList().get(count).getQlty(),
                                        separationController.SList.getList().get(count).getHtype(),                                       
                                        separationController.SList.getList().get(count).getcolor(),
                                        separationController.SList.getList().get(count).getMeatWithSeed() + " kg",
                                        separationController.SList.getList().get(count).getMeatWithoutSeed() + " kg",
                                        "In Separation", "Completed"});
            }
            count++;
             }
            dateStart = dateStart.plusDays(1);
            System.out.println(dateStart);
            i++;
          
        }
    }
    
    public void populateTablePackaged(int year, int month, int date, long number){
        DefaultTableModel tblModel = (DefaultTableModel)jTablePackaged.getModel();
        
        LocalDate dateStart = LocalDate.of(year, month, date);
        long i = 0;
        while(i != number){
        
            int count = 0;     
            
        while(count != packagingController.PList.getList().size()){
            
            if(packagingController.PList.getList().get(count).equalsDate(dateStart) != false){
            
            tblModel.addRow(new Object[] {packagingController.PList.getList().get(count).getDatePackaged(),
                                        packagingController.PList.getList().get(count).getDateOpened(),
                                        packagingController.PList.getList().get(count).getDateRecieved(),
                                        packagingController.PList.getList().get(count).getVrty(),
                                        packagingController.PList.getList().get(count).getQlty(),
                                        packagingController.PList.getList().get(count).getHtype(),                                       
                                        packagingController.PList.getList().get(count).getPcsPackaged(),
                                        "In Packaging", "Completed"});
            }
            count++;
        }
            dateStart = dateStart.plusDays(1);
            System.out.println(dateStart);
            i++;
          
        }
    }
    
    public void populateTableOpened(int year, int month, int date, long number){
        DefaultTableModel tblModel = (DefaultTableModel)jTableOpened.getModel();
        
        LocalDate dateStart = LocalDate.of(year, month, date);
        
        long i = 0;
        while(i != number){
        
            int count = 0;
        
            while(count != openedController.OList.getList().size()){
            
            if(openedController.OList.getList().get(count).equalsDate(dateStart) != false){
            
            int val = openedController.OList.getCurrentProcess(openedController.OList.getList().get(count));
            
           
            
            tblModel.addRow(new Object[] {openedController.OList.getList().get(count).getDateOpened(),
                                        openedController.OList.getList().get(count).getDateRecieved(),
                                        openedController.OList.getList().get(count).getVrty(),
                                        openedController.OList.getList().get(count).getQlty(),
                                        openedController.OList.getList().get(count).getHtype(),
                                        openedController.OList.getList().get(count).getPulpWeight(),
                                        openedController.OList.getList().get(count).getPcsOpened(),
                                        statusCheck(val), statusCheck(val)});
            }
            count++;
            }
            dateStart = dateStart.plusDays(1);
            System.out.println(dateStart);
            i++;
          
        }
    }
    
    public void populateTableReceived(int year, int month, int date, long number){
        DefaultTableModel tblModel = (DefaultTableModel)jTableReceived.getModel();
        LocalDate dateStart = LocalDate.of(year, month, date);
        
        
        long i = 0;
        while(i != number){
        
            int count = 0;
            while(count != recievedController.RList.getList().size()){

                if(recievedController.RList.getList().get(count).equalsDate(dateStart) != false){
                   
                    int val = recievedController.RList.getCurrentProcess(recievedController.RList.getList().get(count));


                    tblModel.addRow(new Object[] {recievedController.RList.getList().get(count).getDateRecieved(),
                                                recievedController.RList.getList().get(count).getVrty(),
                                                recievedController.RList.getList().get(count).getQlty(),
                                                recievedController.RList.getList().get(count).getHtype(),
                                                recievedController.RList.getList().get(count).getfrtWeight(),
                                                recievedController.RList.getList().get(count).getPieces(),
                                                statusCheck(val), statusCheck(val)});

                }
                else{
                    System.out.print(i + " ");
                }
                count++;  
            }
            dateStart = dateStart.plusDays(1);
            System.out.println(dateStart);
            i++;
        }
    }
    
    public String statusCheck(int val){
        switch (val){
            case 0: 
                return "In Recieving";
                            
            case 1:
                return "In Opening";
                           
            case 2:
                return "In Packaging";
              
            case 3:
                return"In Separation";
                            
        }
    return null;
    }
    
    public String currentCheck(int val){
         if (val > 1){
                        return "Completed";
                    }
                    else
                        return "Not Completed";
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDisplayDateFromTo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDisplayDateFromTo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDisplayDateFromTo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDisplayDateFromTo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDisplayDateFromTo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableOpened;
    private javax.swing.JTable jTablePackaged;
    private javax.swing.JTable jTableReceived;
    private javax.swing.JTable jTableSeparated;
    // End of variables declaration//GEN-END:variables
}
